globalvar nebula_ps; nebula_ps = part_system_create()
globalvar nebula_pt; nebula_pt = part_type_create()
globalvar nebula_pe; nebula_pe = part_emitter_create(nebula_ps)
part_system_depth(nebula_ps, 11)
part_system_draw_order(nebula_ps, 1)
part_type_orientation(nebula_pt, 0, 359, 0, 0, 1)
part_type_speed(nebula_pt, 0.2, 0.2, 0, 0)
part_type_direction(nebula_pt, 0, 359, 0, 0)
part_type_life(nebula_pt, 480, 640)
part_type_size(nebula_pt, 1, 4, 0, 0)
part_type_scale(nebula_pt, 1, 1)
part_type_gravity(nebula_pt, 0, 270)
part_type_blend(nebula_pt, 0)
part_type_sprite(nebula_pt, spr_nebula, 0, 0, 1)
part_type_alpha3(nebula_ps, -1, 0.25, -1)
part_type_colour_rgb(nebula_ps, c_white, c_white, c_white, c_white, c_white, c_white)
